swagger: "2.0"
info:
  version: "0.0.1"
  title: OdyC3
# during dev, should point to your local machine
# basePath prefixes all resource paths 
basePath: /api
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /solution:
    # binds a127 app logic to a route
    x-swagger-router-controller: solution
    post:
      description: Register a new solution proposual
      operationId: play
      parameters:
        - name: solution
          in: body
          description: The solution proposual
          schema:
            $ref: "#/definitions/Solution"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/OkResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /winner:
    # binds a127 app logic to a route
    x-swagger-router-controller: solution
    get:
      description: Return the winner
      operationId: winner
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/WinnerResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  OkResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Solution:
    properties:
      email:
        type: string
      play:
        type: array
        items: 
          type: integer
          format: int32
  WinnerResponse:
    properties:
      winner:
        type: string